version: "3.8"
services:
  records:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    command: npm start
